scrollingTFabout.addText("<br /><b>ABOUT THE FILM</b>",false, false);

scrollingTFabout.addText("<br />Adapted by Ethan Hawke from his own novel of the same name, THE HOTTEST STATE is a bittersweet romance that distills the joy, pain, erotic highs, and emotional lows of first love.  Ethan Hawke directs and co-stars in the film along with Mark Webber, Catalina Sandino Moreno, Sonia Braga with Laura Linney and Michelle Williams.",false, false);


scrollingTFabout.addText("<br />Days before his 21st birthday, William (Mark Webber), an actor, meets and quickly falls madly in love with Sara (Oscar-nominee Catalina Sandino Moreno), a seductive yet elusive singer/songwriter. The film follows William from a Lower East Side tenement to a Mexican hotel room to a snowbound weekend in Connecticut to a sweltering homecoming in the hottest state of all – Texas – in the pursuit of Sara.  His stubborn and sweetly innocent quest to find someone who loves him as much as he loves her may not lead to happiness, but surely leads to newfound maturity.",false, false);

scrollingTFabout.addText("<br /><b>ABOUT THE PRODUCTION</b>",false, false);


scrollingTFabout.addText("<br /><i>My heart is gold.  What will you give me for it?</i>",false, false);

scrollingTFabout.addText("\t<br />- Tennessee Williams",false, false);

scrollingTFabout.addText("<br />Adapted by Ethan Hawke from his novel of the same name, THE HOTTEST STATE explores the joy, pain, erotic highs, and emotional lows of first love.  William (Mark Webber) is a modern-day Romeo, a young actor so in love with the idea of love that he recklessly leaps into a romance.  The object of his affection is Sara (Catalina Sandino Moreno), an aspiring singer who is more cautious and down-to-earth in her approach to relationships.  With great wit, charm, and insight, Hawke, who also serves as director of the film, chronicles his appealing young heros quest to find a woman who loves him as much as he loves her, a pursuit destined to lead straight to heartbreak.  Joining Webber and Sandino Moreno in an impressive ensemble cast are Laura Linney and Ethan Hawke, who play Williams parents, Michelle Williams, and Sonia Braga. THE HOTTEST STATE also features music by awarding-winning composer Jesse Harris, who has created a score that expresses all the magic  and the mysteries  of the human heart.",false, false);
scrollingTFabout.addText("<br />Hawkes novel, which was published in 1997, set out to explore new territory.  I felt like there had been a tremendous amount of fiction about women getting their hearts broken and the loss and weakness they felt when their love was abandoned, but I never read a novel about a man going through it so, I tried my hand at writing one, recalls Hawke.  Critics called the book touching, engaging, and beguiling, and said it was full of the freshness of love and the agony of loss.  While THE HOTTEST STATE is not a memoir, it falls into the category of autobiographical fiction and is definitely drawn from Hawkes life experiences. ",false, false);

scrollingTFabout.addText("<br />Hawke decided to adapt his novel while he was directing his film, CHELSEA WALLS.  When he cast Mark Webber in that project, Hawke realized that the young actor matched his image of the character William in THE HOTTEST STATE.   Mark Webber was the catalyst for me to start working on the film adaptation, Hawke explains.  He instantly saw qualities in Webbinnocence, sensitivity, and earnestness  that would bring the character to life.  Webber, who admits to having had his share of broken hearts, identified with the character.  The thing I like the most about the film is that it speaks to any age range, he says.  You can remember what it was like to feel that way, or you could be feeling it right now.",false, false);

scrollingTFabout.addText("<br />Casting the role of Sara, was a more difficult process.  Sara was never defined as clearly because she was an ambiguous figure in William's psyche, says Hawke. She is not just a frivolous beauty, but a woman worth impaling yourself over. Catalina Sandino Moreno fit the bill. She intrinsically carried the mystery, passion, and soul of a true heartbreaker.  Nominated for an Academy Award for her astonishing performance in Maria Full of Grace, Sandino Moreno artfully creates a Sara who is at once both real and idealized.  When Hawke first approached her with the idea, she had difficulty imagining herself in a romance.  But, as soon as she read the script, Sandino Moreno wanted to play the role.  I read it in half an hour and I was crying, she remembers.  It was something that had happened to me. It was so pure and personal that I had to do it.",false, false);

scrollingTFabout.addText("<br />For Samantha, the beautiful and complicated young woman who was Williams previous romantic obsession, Hawke selected Michelle Williams, who was nominated for an Academy Award for her performance in Brokeback Mountain.  Laura Linney,  an Academy Award nominee for Kinsey and You Can Count on Me, plays Jesse, Williams eccentric mother, and Hawke, nominated for two Academy Awards  Best Supporting Actor for Training Day and Best Adapted Screenplay for Before Sunset  plays Vince, Williams errant father.  This stellar cast is rounded out by Sonia Braga, who plays Saras mother.",false, false);

scrollingTFabout.addText("<br />Hawkes perceptive story of the agonies of young love is timeless in its themes. He was happy to find that he did not have to make substantial changes when he set out to adapt his novel. The changes were mostly superficial. Updating the time period, for example (the book took place in the 90s) was one change we made. What is substantive to the story doesn't alter whether the characters are text messaging each other or delivering hand written notes, he points out.   As for the challenges of directing, Obviously working with a modest budget to tell a story that is dear to your heart presents many challenges, but I would be lying if I didn't admit that working with my collaborators provided some of the most joyous experiences of my life, professional or otherwise, Hawke says. And the cinema gods would strike me dead if I lodged even one complaint.",false, false);

scrollingTFabout.addText("<br />One of Hawkes most significant collaborations was with composer Jesse Harris.  Since Sandino Morenos character is a musician and a songwriter, Hawke knew her music would set the tone for the film.  He approached Harris, whom he had known since the early 90s.  There was always something slightly irritating about how much girls were enamored by his casual, big smiling &quot;hey let's all just hang&quot; kinda demeanor, Hawke recalls.  The truth was that as I watched him and his music grow up, it became obvious that I was just jealous  there was and is something deeply talented about the guy  wise, simple, clean, elegant and disarmingly unaffected.  More than anything else, he is a true romantic.",false, false);

scrollingTFabout.addText("<br />Harris read the script and was incredibly insightful about the story and its themes.  He gave Hawke about 50 songs that would be good choices for Sara and wrote two new ones, including &quot;Never See You.&quot;  I was overwhelmed by the quality and by how perfectly matched his writing was to my aspirations for the tone and mood of the film, says Hawke.  An idea began to develop: What if we scored the film entirely with original songs written by Jesse, and performed by contemporary artists, hand-picked to match certain scenes? We could approach the ideal artist to perform the song and score the entire film this way.  All the music in the film would be original. For example, the movie is scripted to open with a flashback to late 70's in Texas: Willie Nelson doing Jesse's &quot;Always Seem to Get Things Wrong&quot; would be perfect. Later in the film our hero is walking through Brooklyn so depressed he feels his eyes might bleed: Cat Power doing &quot;Its Alright to Fail&quot; would nail it.  Who should be playing in the background of a Williamsburg party?  Bright Eyes. Falling so madly in love you forget your own name? Norah Jones, &quot;World of Trouble.&quot;",false, false);
scrollingTFabout.addText("<br />Harris quickly became an integral part of the making of THE HOTTEST STATE, working closely with Hawke to realize their dream of an original and innovative score. I sat with him for hours at a time as we imagined the music cues and found songs to correspond to what I imagined the filmmaking would be doing.  His voice as a writer became kind of a third character, a Greek Chorus, echoing and supporting the characters and the themes. ",false, false);

scrollingTFabout.addText("<br />Harris music is expressive of young love and young pain. As it turns out, I have a lot of songs on the subject! says Harris. The process of creating musical equivalents for the characters' emotions was a matter of choosing the right song for the right singer.  Ethan listened to about 70 songs to pick the ones he wanted.  The two new ones, Never See You and It Will Stay with Us, are more reflexive.  For the instrumental score, I assembled musicians in the studio and performed the music while watching the scenes.  Ethan would direct us, explaining how he wanted the music to change as the scene progressed.  The result is a unique musical experience: Harris distinctive music integrates perfectly with Hawkes images.",false, false);

scrollingTFabout.addText("<br />Hawke fulfills his ambition of creating a vivid and emotionally-charged portrait of a young man caught up in the bittersweet throes of love.  Young love is fickle, says Hawke.  I don't think relationships have changed a great deal. Having spent my life doing plays by Shakespeare, Chekhov, Tennessee Williams, and the like, you notice, in regards to romance, things haven't changed very much at all.",false,true);
//scrollingTFsoundtrack.enableScroller();